spring:
  application:
    name: MyI18n
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cdb-7yrw31k6.sql.tencentcdb.com:59480/myi18n?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: Tuan191018
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
server:
  servlet:
    context-path: /
